all=libscredis.so test
all:$(all)
libscredis.so:scredis.h scredis.c
	gcc -Wall -g -fPIC -shared -o libscredis.so scredis.c 
test:test.c scredis.c scredis.h 
	gcc -Wall -g -o test test.c scredis.c -ldie
clean:
	rm $(all)

install:
	cp $(all) /usr/local/lib
	cp scredis.h /usr/local/include
uninstall:
	cd /usr/local/lib && rm $(all)
	rm /usr/local/include/scredis.h
